replicaCount: 1

image:
  repository: localhost:5000/istio-client-demo
  tag: latest
  pullPolicy: IfNotPresent

rbac:
  create: true

serviceAccount:
  create: true
  name: istio-client-demo

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

version: "v1"